switch:
  - platform: gpio
    pin: 18
    name: "LED Lamp"
    id: led_lamp

sensor:
  - platform: dht
    pin: 19
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    model: DHT11

  - platform: adc
    pin: 34
    name: "Photoresistor"

  - platform: ld2410
    moving_distance:
      name: Jarak Target Gerak
      id: moving_distance
    still_distance:
      name: Jarak Target Diam
      id: still_distance
    detection_distance:
      name: Jarak Umum
      id: radar_detection_distance
    g0:
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1:
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2:
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3:
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4:
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5:
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6:
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7:
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8:
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy

ld2410:
  id: ld2410_radar

uart:
  tx_pin: 15
  rx_pin: 2
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

number:
  - platform: ld2410
    timeout:
      name: Radar Timeout
    max_move_distance_gate:
      name: Jarak Maks Gerak
    max_still_distance_gate:
      name: Jarak Maks Diam
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold

binary_sensor:
  - platform: ld2410
    has_target:
      name: Radar Target
      id: radar_has_target
    has_moving_target:
      name: Deteksi Gerak
    has_still_target:
      name: Deteksi Diam

output:
  - platform: ledc
    pin: 27
    id: fan_output
    frequency: 25000 Hz

fan:
  - platform: speed
    output: fan_output
    name: "Cooling Fan"
